# Default values for SubscriptionProcessorChart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: danigian/aks-servicebus-health
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources:
  limits:
    cpu: 300m
    memory: 256Mi
  requests:
    cpu: 300m
    memory: 256Mi

nodeSelector: {}

tolerations: []

affinity: {}

PodIdentity:
  Enabled: false
  BindingLabel: ""

ServiceBusConfiguration:
  MinimumAllowedBackoffTime: 0
  MaximumAllowedBackoffTime: 30
  MaximumAllowedRetries: 5
  MinimumAllowedGracePeriod: 45
  DefaultGracePeriodInSeconds: 120
  ConnectionString: ""
  EntityPath: ""
  Namespace: ""