name: Building and pushing Docker Image

on:
  push:
    branches:
      - master
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.4.0
      with:
        dotnet-version: 3.1.201
    - run: dotnet test src/ServiceBusSubscriptionProcessor.UnitTest/ServiceBusSubscriptionProcessorUnitTest.csproj
    - name: Build and push Docker images
      uses: docker/build-push-action@v1.0.1
      with:
        # Username used to log in to a Docker registry. If not set then no login will occur
        username: danigian
        # Password or personal access token used to log in to a Docker registry. If not set then no login will occur
        password: ${{secrets.DOCKER_LOGIN_PASSWORD}}
        # Docker repository to tag the image with
        repository: danigian/aks-servicebus-health
        # Comma-delimited list of tags. These will be added to the registry/repository to form the image's tags
        tags: latest
        # Automatically tags the built image with the git short SHA as per the readme
        tag_with_sha: true
        # Path to the build context
        path: src/ServiceBusSubscriptionProcessor
